first:
    pattern:  /first/{name}
    defaults: { _controller: FirstPageBundle:FirstPage:index }

main_menu:
    pattern:  /menu/{name_tab}
    defaults: { _controller: FirstPageBundle:MainMenu:select }

first_page_homepage:
    path:     /
    defaults: { _controller: FirstPageBundle:Default:index }
