first:
    pattern:  /first
    defaults: { _controller: FirstPageBundle:FirstPage:index }

main_menu:
    pattern:  /menu/{name_tab}
    defaults: { _controller: FirstPageBundle:MainMenu:select }

login:
    pattern:  /login
    defaults: { _controller: FirstPageBundle:AdminPage:login }

login_check:
    pattern:  /login_check

admin:
    pattern:  /admin
    defaults: { _controller: FirstPageBundle:AdminPage:admin }

default_page_homepage:
    path:     /
    defaults: { _controller: FirstPageBundle:FirstPage:index }
