first:
    pattern:  /first/{name}
    defaults: { _controller: FirstPageBundle:FirstPage:index }

second:
    pattern:  /second/{name}
    defaults: { _controller: FirstPageBundle:SecondPage:index }

first_page_homepage:
    path:     /
    defaults: { _controller: FirstPageBundle:Default:index }
