first:
    pattern:  /first
    defaults: { _controller: FirstPageBundle:FirstPage:index }

main_menu:
    pattern:  /menu/{name_tab}
    defaults: { _controller: FirstPageBundle:MainMenu:select }

login:
    pattern:  /login
    defaults: { _controller: FirstPageBundle:SecurityPage:login }

login_check:
    pattern:  /login_check

logout:
    path:  /logout

admin:
    pattern:  /admin
    defaults: { _controller: FirstPageBundle:SecurityPage:admin }

user:
    pattern:  /user
    defaults: { _controller: FirstPageBundle:SecurityPage:user }

account:
    pattern:  /account
    defaults: { _controller: FirstPageBundle:SecurityPage:account }

registration:
    pattern:  /registration
    defaults: { _controller: FirstPageBundle:SecurityPage:registration }

writeregdata:
    pattern:  /writeregdata
    defaults: { _controller: FirstPageBundle:SecurityPage:writeregdata }

default_page_homepage:
    path:     /
    defaults: { _controller: FirstPageBundle:FirstPage:index }
