first:
    path:  /first
    defaults: { _controller: FirstPageBundle:FirstPage:index }

main_menu:
    path:  /menu/{name_tab}
    defaults: { _controller: FirstPageBundle:MainMenu:select }

login:
    path:  /login
    defaults: { _controller: FirstPageBundle:SecurityPage:login }

login_check:
    path:  /login_check

logout:
    path:  /logout

admin:
    path:  /admin/{name_tab}
    defaults: { _controller: FirstPageBundle:SecurityPage:admin }

account:
    path:  /account
    defaults: { _controller: FirstPageBundle:SecurityPage:account }

registration:
    path:  /registration
    defaults: { _controller: FirstPageBundle:SecurityPage:registration }

writeregdata:
    path:  /writeregdata
    defaults: { _controller: FirstPageBundle:SecurityPage:writeregdata }

previeworder:
    path:  /previeworder
    defaults: { _controller: FirstPageBundle:Order:previeworder }

receiveorder:
    path:  /receiveorder
    defaults: { _controller: FirstPageBundle:Order:receive }

update_confirm_order:
    path:  /update_confirm_order
    defaults: { _controller: FirstPageBundle:Order:update_confirm }

export:
    path:  /export
    defaults: { _controller: FirstPageBundle:Admin:export }

update_menu:
    path:  /update_menu
    defaults: { _controller: FirstPageBundle:Admin:update_menu }

readorders:
    path:  /readorders/{order}/{orderstatus}/{idorder}
    defaults: { _controller: FirstPageBundle:Admin:readorders }

exportorder:
    path:  /exportorder
    defaults: { _controller: FirstPageBundle:Admin:exportorder }

acceptorder:
    path:  /acceptorder
    defaults: { _controller: FirstPageBundle:Admin:acceptorder }

login_ajax:
    path:  /login_ajax
    defaults: { _controller: FirstPageBundle:SecurityAjax:login }

default_page_homepage:
    path:     /
    defaults: { _controller: FirstPageBundle:FirstPage:index }
