<?php

namespace First\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cold_dishes_meatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cold_dishes_meatRepository extends EntityRepository
{
}
