<?php

namespace First\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * dessertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dessertRepository extends EntityRepository
{
}
