<?php

namespace First\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * main_menuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class main_menuRepository extends EntityRepository
{
}
