<?php

namespace First\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * soupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class soupRepository extends EntityRepository
{
}
