# src/Acme/HelloBundle/Resources/config/routing.yml
hello:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }


acme_hello_homepage:
    path:     /
    defaults: { _controller: AcmeHelloBundle:Default:index }

