First\PageBundle\Entity\soup:
    type: entity
    table: null
    repositoryClass: First\PageBundle\Repository\soupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        portion:
            type: string
            length: 255
        cost:
            type: decimal
            precision: 10
            scale: '2'
        composition:
            type: text
    lifecycleCallbacks: {  }
