First\PageBundle\Entity\visitors:
    type: entity
    table: null
    repositoryClass: First\PageBundle\Repository\visitorsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nameV:
            type: string
            length: 255
            column: name_v
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        groupV:
            type: string
            length: 255
            column: group_v
    lifecycleCallbacks: {  }
