First\PageBundle\Entity\zakaz:
    type: entity
    table: null
    repositoryClass: First\PageBundle\Repository\zakazRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idZak:
            type: string
            length: 255
            column: id_zak
        dateT:
            type: datetime
            column: date_t
        portion:
            type: string
            length: 255
        idDishes:
            type: integer
            column: id_dishes
        cost:
            type: decimal
            precision: 10
            scale: '2'
        nameTab:
            type: string
            length: 255
            column: name_tab
        accept:
            type: boolean
    lifecycleCallbacks: {  }
